#!/usr/bin/env bash

echo "NOTICE: Tested with"
echo "- Node.js 8.15.0 (as node in $PATH)"
echo "- Npm 6.4.1 (as npm in $PATH)"
echo "- clang (tested with 3.7)"
echo "- make"
echo "- git"
echo "- python 2.7 (as python in $PATH)"

read  -n 1 -p "Press any key to continue" cont

printf "\n[+] Fetching ExpoSE (PLDI)\n"

rm -rf ./PLDI/
git clone https://github.com/ExpoSEJS/ExpoSE.git PLDI
git checkout 89e72c60328fa29ecaae87c9541a0d1b0fb243d5

echo "[+] Setup Crawlr"
(cd crawlr; npm install)

echo "[+] Setup ExpoSE (Legacy)"
(cd SPIN; npm install)

echo "[+] Setup PLDI ExpoSE"
(cd PLDI; npm install)

echo "[+] Setup Feature Tester"
(cd FeatureTester; npm install)

echo "Installed. Preparing to run unit tests."
echo "If any tests fail, please use the VM image"

read -n 1 -p "Press any key to continue" cont
(cd PLDI; npm test)
(cd SPIN; ./expoSE test_suite)
