#!/usr/bin/env bash

echo "NOTICE: Tested with"
echo "node 8.15.0"
echo "npm 6.4.1"
echo "clang 3.8.0"
echo "build-essential"

read  -n 1 -p "Press any key to continue" cont

printf "\n[+] Fetching ExpoSE (PLDI)\n"

rm -rf ./PLDI/
git clone https://github.com/ExpoSEJS/ExpoSE.git PLDI

echo "[+] Setup Crawlr"
(cd crawlr; npm install)

echo "[+] Setup ExpoSE (Legacy)"
(cd SPIN; npm install)

echo "[+] Setup PLDI ExpoSE"
(cd PLDI; npm install)

echo "Installed. Preparing to run unit tests."
echo "If any tests fail, please use the VM image"

read -n 1 -p "Press any key to continue" cont
(cd PLDI; npm test)
(cd SPIN; ./expoSE test_suite)
